language: python
sudo: required
dist: trusty
cache:
  directories: [ '$HOME/lxc' ]
  pip: true
env:
  matrix:
  - LXC_DISTRO=debian LXC_RELEASE=jessie
  - LXC_DISTRO=ubuntu LXC_RELEASE=xenial
  - LXC_DISTRO=centos LXC_RELEASE=7
  global:
  - secure: xGVCBlqG1arf1bztyhFR7v3fqGrRHrZYaFPzSVhVu53F+9cNdxnqoiWurNvui7g44GwTZWVgCTiENLuuHMLcObgFLgYuwj1FlOljgpJ2BTL7/HUH8ACiujkXSm/SbniX5dZMVy2ZIJF8+/956MkaxQ1fypgMa7c3/x7BTe2oFuI9ebgP88tbVpU4lToK+mlTGSJ7LQ89afdoj7LditwJbmTNBevbVagYij5R11CoP9JSLo+G2L4G2rwCIWCIH4Ea3D4iLdcHxxjX/Xvzjs7iOa7gy+1icwQYiFw9BsRM/TD17BLM35d+uCT+02XXyNoOH7+RwoBx1XfMq5I9huec6v+pmAYpHB4QBQvSnmmM00MQ68HgRxxEOtepcm68pzG0M4ZWFV1IY8L3JL6F9F7qOGYbnjKGMlNuLalIglPkFUJneyVGPKJ8mZ/wtvUGZlZ79lwshsvGfwNv3sE2soh01Wiupckx0bLRExz50WUHmHUeMoumRQ1GD7KTXl3qOe7rA7MEb52SB4Npo/NmCsXRKDhWyB1+QwoN94SkgiaLGxDHJsZ6fdsm+G4D8Kz3JASR8VDujXW0XOiT48N1HPVlvmKCRSMGf4fn4Z85e1XOoQUz8vG+4O9RpygUZ4iEZcXntBvIWcJ4xXeT2oy2jNfEIbvL7l32FLqYcqcsi1IrPeo=
before_cache:
  - sudo mkdir $HOME/lxc && sudo tar cf $HOME/lxc/cache.tar /var/cache/lxc/ && sudo chown $USER. $HOME/lxc/cache.tar
install:
- sudo tar xf $HOME/lxc/cache.tar -C / || true
- sudo apt-get install -y expect-dev
- pip install ansible
- ansible --version
- printf "$VAULT_PASSWORD" > .vault_password
- printf '[defaults]\nroles_path=../\nvault_password_file=.vault_password\ncallback_whitelist=profile_tasks'  >ansible.cfg
- ansible-galaxy install lae.travis-lxc williamyeh.oracle-java lae.dse_repo
- ansible-playbook -vvv tests/install.yml
script:
- ansible-playbook tests/test.yml -i tests/inventory --syntax-check
- ansible-playbook tests/test.yml -i tests/inventory
- unbuffer ansible-playbook -vvv tests/test.yml -i tests/inventory >/tmp/idempotency.log 2>&1
- 'grep -A1 "PLAY RECAP" /tmp/idempotency.log | grep -qP "changed=0.*failed=0" && (echo "Idempotence:
  PASS"; exit 0) || (echo "Idempotence: FAIL"; cat /tmp/idempotency.log; exit 1)'
- ansible -m shell -a "PAGER=cat journalctl -xu dse" -i tests/inventory all
- ansible -m shell -a "nodetool status" -i tests/inventory all
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: hoEDQnPRXVX1hOUJv/JfoU9FO+115FxCm5uy8WTbP9CWhfvr/n0QLSMXSKPjGQzbHLPCPJDYMK/FvO2MdRw3YW+n9iw7KCv56lHS0dRbQug5kWMCMKM74o+0CH72LIlfQHChcA2v32IiolHOEYUM+D+qxz+a3KXUDUaG+PMTz2DDRzWCzkjF9pwfmK7C0O4o9yyqMFl+GOQ/z2ug6VBDtWIFPnhV+Xf7SkoELzZ7K7SzpeNof5O0Zopuc0MCIZZktl2fS60cqHyUgoMIR17OfyO2gDhav4ghprxOa7wRIv+6Xala0618IXXw/0QWjLW1vdAPSp4z7OFKIEKe8E86g97aOzlkpUC8MvbrgSY/y5xDEfGgAc3NWHpT86a45kd5qLBzqFKgznLZPAScWUF1hFlppH5uXsytXqAf6szhfXdvpm4C8LvjygXi6xPbTrbmoUaQUOx+ZI+5FQ4u3bbHQUiqQ7FK0r4ZDrtI/amsR3qCKimR4qZVI+x2JM4TrsWgSjcItSdY/Bsaa8a1O6eu+GpdNSfR1N6adrljKdmMHfq/lFjDwina+iz14iTyye0G4Pm7mzDqj+9J5O77Ws1a/8i0RwS2X7JzL9+88KJWIgvi6joHzZOkJGt8tbC8v+NeEC8GOBGTo17hQ4NQHTlZAtDYeA0FMYGSyKX3tSPi5dA=
